
export const OPEN_SNACKBAR = "OPEN_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";





// Restaurants
export const GET_ALL_RESTAURANTS = "GET_ALL_RESTAURANTS";
export const GET_SINGLE_RESTAURANT = "GET_SINGLE_RESTAURANT";
export const RESTAURANT_ERROR = "RESTAURANT_ERROR";
export const RESTAURANT_LOADING = "RESTAURANT_LOADING";

// Cart
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const GET_NUMBER_CART = 'GET_NUMBER_CART';
export const ADD_CART = 'ADD_CART' ;
export const UPDATE_CART = 'UPDATE_CART';
export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_CART = 'DELETE_CART';


// Users
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT"
export const SET_IS_LOADING = "SET_IS_LOADING"



